server.port=8084
spring.application.name=appliance-service
spring.config.import=classpath:application-db.properties
WALLMART_DB_BOOTSTRAP=false
spring.graphql.graphiql.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
