server.port=8081
spring.application.name=product-service
spring.config.import=classpath:application-db.properties
WALLMART_DB_BOOTSTRAP=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [sessionId=%X{sessionId}] %logger{36} - %msg%n
