server.port=8082
spring.application.name=cart-service
spring.config.import=classpath:application-db.properties
WALLMART_DB_BOOTSTRAP=false
wallmart.product-service-base-url=http://127.0.0.1:8081
wallmart.payment-service-base-url=http://127.0.0.1:8083
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [sessionId=%X{sessionId}] %logger{36} - %msg%n
