apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallmart.fullname" . }}-app-config
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
data:
  WALLMART_PRODUCT_SERVICE_BASE_URL: {{ .Values.appConfig.productServiceBaseUrl | quote }}
  WALLMART_PAYMENT_SERVICE_BASE_URL: {{ .Values.appConfig.paymentServiceBaseUrl | quote }}
  WALLMART_DEMO_CHAOS_ENABLED: {{ .Values.appConfig.demoChaosEnabled | quote }}
