apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallmart.fullname" . }}-nginx
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ include "wallmart.ecommerceWebContainerPort" . }};
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        gzip on;
        gzip_types text/css application/javascript application/json image/svg+xml;

        underscores_in_headers on;

        location /productsearch {
            proxy_pass http://{{ .Values.serviceNames.productService }}:{{ .Values.productService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
        }

        location /getcart {
            proxy_pass http://{{ .Values.serviceNames.cartService }}:{{ .Values.cartService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_request_headers on;
        }

        location /addproduct {
            proxy_pass http://{{ .Values.serviceNames.cartService }}:{{ .Values.cartService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /clearcart {
            proxy_pass http://{{ .Values.serviceNames.cartService }}:{{ .Values.cartService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /checkout {
            proxy_pass http://{{ .Values.serviceNames.cartService }}:{{ .Values.cartService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /pay {
            proxy_pass http://{{ .Values.serviceNames.paymentService }}:{{ .Values.paymentService.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
