{{- if .Values.openshift.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallmart-app
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceNames.ecommerceWeb }}
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
{{- if .Values.sqlserver.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceNames.sqlserver }}
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.synthetic.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: playwright-loop
  namespace: {{ include "wallmart.namespace" . }}
  labels:
    {{- include "wallmart.labels" . | nindent 4 }}
{{- end }}
{{- end }}
