server.port=8083
spring.application.name=payment-service
spring.config.import=classpath:application-db.properties
WALLMART_DB_BOOTSTRAP=false
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [sessionId=%X{sessionId}] %logger{36} - %msg%n
